### ISSUE TITLE
Brainstorm Dumping Grounds (Things I Might Want To Do On This Project) + Tasks To Complete

### ISSUE THREAD

**Issue by ivrouwe** [ivrouwe/portfolio#2]
## Things I Might Want To Do On This Project
- [ ] Add an HTML `<form>` where users can change the `<body>` `font-size` and refresh the page to see the changes.
- [ ] Add additional `<img>`s and use `srcset` (where appropriate)
## Tasks To Complete
- [ ] Improve style of Document (".document") module
